name: Build ANGLE - Linux x64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPOT_TOOLS_PATH: depot_tools

    steps:
      - name: Checkout Chromium Source Code
        uses: actions/checkout@v4  # 更新到 v4 版本
        with:
          repository: chromium/chromium
          path: chromium

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "::add-path::$(pwd)/depot_tools"

      - name: Verify depot_tools in PATH
        run: |
          which gclient

      - name: Sync Chromium Dependencies
        working-directory: chromium
        run: gclient sync

      - name: Configure ANGLE Build (GN)
        working-directory: chromium/third_party/angle
        run: |
          gn gen out/Debug --args='target_os="linux" target_cpu="x64" is_debug=true angle_build_gl=true angle_build_gles=true angle_build_vulkan=true angle_build_d3d=false angle_build_metal=false'

      - name: Build ANGLE (Ninja)
        working-directory: chromium/third_party/angle
        run: ninja -C out/Debug angle_tests -j$(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # 更新到 v4 版本
        with:
          name: angle-linux-x64-debug-build
          path: chromium/third_party/angle/out/Debug
