name: Build ANGLE - Linux x64 (Environment Files)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPOT_TOOLS_PATH: depot_tools # 定义 depot_tools 目录的变量 (虽然这里定义了，但实际上会被 Environment Files 覆盖，可以删除这个 env 定义)

    steps:
      - name: Checkout Chromium Source Code
        uses: actions/checkout@v4
        with:
          repository: chromium/chromium
          path: chromium

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "DEPOT_TOOLS=$(pwd)/depot_tools" >> $GITHUB_ENV # 设置 DEPOT_TOOLS 环境变量 in $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/depot_tools" >> $GITHUB_ENV # 将 depot_tools 加入 PATH in $GITHUB_ENV (为了简化)

      - name: Verify depot_tools in PATH
        run: |
          echo "PATH from ENV file: $PATH" # 检查 PATH 环境变量
          which gclient # 验证 gclient 是否在 PATH 中

      - name: Sync Chromium Dependencies
        working-directory: chromium
        run: gclient sync

      - name: Configure ANGLE Build (GN)
        working-directory: chromium/third_party/angle
        run: |
          gn gen out/Debug --args='target_os="linux" target_cpu="x64" is_debug=true angle_build_gl=true angle_build_gles=true angle_build_vulkan=true angle_build_d3d=false angle_build_metal=false'

      - name: Build ANGLE (Ninja)
        working-directory: chromium/third_party/angle
        run: ninja -C out/Debug angle_tests -j$(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angle-linux-x64-debug-build
          path: chromium/third_party/angle/out/Debug
