name: Build ANGLE - Android ARM64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPOT_TOOLS_PATH: depot_tools
      ANDROID_NDK_VERSION: r25c # 可以根据需要更改 NDK 版本

    steps:
      - name: Checkout Chromium Source Code
        uses: actions/checkout@v4
        with:
          repository: chromium/chromium
          path: chromium
          fetch-depth: 1

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "DEPOT_TOOLS=$(pwd)/depot_tools" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/depot_tools" >> $GITHUB_ENV

      - name: Verify depot_tools in PATH
        run: |
          echo "PATH from ENV file: $PATH"
          which gclient

      - name: Install Android NDK
        run: |
          mkdir -p android-ndk
          wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
          unzip android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip -d android-ndk
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk/${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/android-ndk/${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV

      - name: Configure gclient
        working-directory: chromium
        run: gclient config https://chromium.googlesource.com/chromium/chromium.git

      - name: Sync Chromium Dependencies
        working-directory: chromium
        run: gclient sync

      - name: Configure ANGLE Build (GN) - Android ARM64
        working-directory: chromium/third_party/angle
        run: |
          gn gen out/Android_ARM64 --args='target_os="android" target_cpu="arm64" is_debug=false angle_build_gl=false angle_build_gles=true angle_build_vulkan=true angle_build_d3d=false angle_build_metal=false'

      - name: Build ANGLE (Ninja) - Android ARM64
        working-directory: chromium/third_party/angle
        run: ninja -C out/Android_ARM64 angle_library -j$(nproc) # 构建 angle_library 目标

      - name: Upload Build Artifacts - Android ARM64
        uses: actions/upload-artifact@v4
        with:
          name: angle-android-arm64-release-build
          path: chromium/third_party/angle/out/Android_ARM64/libangle.so # 上传 libangle.so 库文件