name: Build ANGLE for Android ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_android_arm64:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$(pwd)/depot_tools" >> $GITHUB_PATH
        echo "DEPOT_TOOLS_METRICS=0" >> $GITHUB_ENV

    - name: Configure gclient
      run: |
        gclient config --spec 'solutions = [
          {
            "url": "https://chromium.googlesource.com/angle/angle.git",
            "managed": False,
            "name": "angle",
            "deps_file": "DEPS",
            "custom_deps": {},
          },
        ]'

    - name: Sync dependencies (gclient sync)
      run: gclient sync --nohooks --no-history --with_branch_heads --with_tags > gclient_sync.log 2>&1

    - name: Set up Android SDK and NDK # 添加设置 Android SDK/NDK 的步骤
      uses: android-actions/setup-android-sdk@latest # 使用 actions/setup-android-sdk action
      with:
        ndk-version: 'latest' # 使用最新的 NDK 版本

    - name: Generate build files (gn gen for Android ARM64)
      run: |
        gn gen out/Android_arm64_Release --args='
          target_os="android"
          target_cpu="arm64"
          is_debug=false
          is_clang=true
          use_custom_libcxx=true
          ndk_path="${ANDROID_NDK_HOME}" # 设置 NDK 路径，使用环境变量
          # --- ANGLE Specific Features ---
          angle_enable_vulkan=true
          angle_enable_gl=true
          # --- Other Common Flags ---
          dcheck_always_on=false
          is_component_build=false
        ' > gn_gen.log 2>&1

    - name: Build ANGLE (ninja)
      run: ninja -C out/Android_arm64_Release > ninja_build.log 2>&1

    - name: Upload ANGLE Android ARM64 libraries
      uses: actions/upload-artifact@v4
      with:
        name: angle-android-arm64-release-libs
        path: |
          out/Android_arm64_Release/libEGL.so
          out/Android_arm64_Release/libGLESv2.so
          out/Android_arm64_Release/libGLESv1_CM.so
        if-no-files-found: error

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          gclient_sync.log
          gn_gen.log
          ninja_build.log
