name: Build ANGLE - Linux x64 (Retry sync with flags)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPOT_TOOLS_PATH: depot_tools

    steps:
      - name: Checkout Chromium Source Code
        uses: actions/checkout@v4
        with:
          repository: chromium/chromium
          path: chromium
          # 使用 fetch-depth: 0 可能会帮助 gclient sync，但会显著增加 checkout 时间。
          # 暂时保持 fetch-depth: 1。
          fetch-depth: 1

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "DEPOT_TOOLS=$(pwd)/depot_tools" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/depot_tools" >> $GITHUB_ENV

      - name: Verify depot_tools in PATH
        run: |
          echo "PATH from ENV file: $PATH"
          which gclient

      - name: Configure gclient
        working-directory: chromium
        run: gclient config https://chromium.googlesource.com/chromium/chromium.git

      # 移除了无效的 'Force gclient to use HTTPS' 步骤

      - name: Sync Chromium Dependencies (Retry on failure with flags)
        working-directory: chromium
        run: |
          set +e # 允许命令失败
          LAST_EXIT_CODE=0
          for i in {1..3}; do # 重试循环 (最多 3 次)
            echo "Attempting gclient sync, attempt $i"
            # 添加 --reset --force --delete_unversioned_trees 和 -v (verbose) 标志
            gclient sync --reset --force --delete_unversioned_trees -v
            LAST_EXIT_CODE=$?
            if [ $LAST_EXIT_CODE -eq 0 ]; then
              break # 如果成功，则跳出循环
            fi
            echo "gclient sync failed with exit code $LAST_EXIT_CODE, retrying in 15 seconds..."
            sleep 15 # 增加重试间隔
          done
          set -e # 重新启用错误时退出

          # 在循环后检查最终退出码
          if [ $LAST_EXIT_CODE -ne 0 ]; then
            echo "gclient sync failed after multiple retries."
            exit $LAST_EXIT_CODE
          fi

      - name: Configure ANGLE Build (GN)
        working-directory: chromium/third_party/angle
        run: |
          gn gen out/Debug --args='target_os="linux" target_cpu="x64" is_debug=true angle_build_gl=true angle_build_gles=true angle_build_vulkan=true angle_build_d3d=false angle_build_metal=false'

      - name: Build ANGLE (Ninja)
        working-directory: chromium/third_party/angle
        run: ninja -C out/Debug angle_tests -j$(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angle-linux-x64-debug-build
          path: chromium/third_party/angle/out/Debug