        run: |
          echo "Starting gclient sync (initial checkout)..."
          date
          vpython # 添加vpython, 为了保证所有依赖都安装完全
          gclient sync -j$(nproc)
          date
          echo "gclient sync (initial checkout) completed."