name: Build ANGLE - Linux x64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Chromium Source Code
        uses: actions/checkout@v3
        with:
          repository: chromium/chromium # 使用 chromium/chromium 仓库，ANGLE 在其中
          path: chromium # 将代码检出到 chromium 目录

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:$(pwd)/depot_tools"

      - name: Sync Chromium Dependencies
        working-directory: chromium
        run: gclient sync

      - name: Configure ANGLE Build (GN)
        working-directory: chromium/third_party/angle
        run: |
          gn gen out/Debug --args='target_os="linux" target_cpu="x64" is_debug=true angle_build_gl=true angle_build_gles=true angle_build_vulkan=true angle_build_d3d=false angle_build_metal=false'

      - name: Build ANGLE (Ninja)
        working-directory: chromium/third_party/angle
        run: ninja -C out/Debug angle_tests -j$(nproc) # 使用所有可用的处理器核心加速编译

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angle-linux-x64-debug-build
          path: chromium/third_party/angle/out/Debug # 上传整个 out/Debug 目录，包含库文件和可执行文件
